// Build data/data.js (window.TBC) from data/references/*.csv
// Mirrors the vs-build-calc MO: CSV references -> single generated data file the SPA includes.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const REF = join(ROOT, 'data', 'references');

// minimal CSV parser (handles quoted fields with commas/newlines)
function parseCSV(text) {
  const rows = [];
  let row = [], field = '', q = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (q) {
      if (c === '"' && text[i + 1] === '"') { field += '"'; i++; }
      else if (c === '"') q = false;
      else field += c;
    } else if (c === '"') q = true;
    else if (c === ',') { row.push(field); field = ''; }
    else if (c === '\r') { /* skip */ }
    else if (c === '\n') { row.push(field); rows.push(row); row = []; field = ''; }
    else field += c;
  }
  if (field.length || row.length) { row.push(field); rows.push(row); }
  return rows;
}
function table(file) {
  const p = join(REF, file);
  if (!existsSync(p)) return [];
  const rows = parseCSV(readFileSync(p, 'utf8')).filter(r => r.some(c => c !== ''));
  const head = rows.shift();
  return rows.map(r => Object.fromEntries(head.map((h, i) => [h, r[i] ?? ''])));
}
const num = v => (v === '' || v == null ? null : Number(v));

// ---- classes (team roster) ----
const classes = table('class.csv').map(r => ({
  id: r.class_id,
  name: r.class_name,
  character: r.character_name,
  act: r.source_act,
  base: { pow: num(r.pow), foc: num(r.foc), spd: num(r.spd), tgh: num(r.tgh), dsc: num(r.dsc),
          agi: num(r.agi), end: num(r.end), wis: num(r.wis), tec: num(r.tec) },
  hpOverride: num(r.hp_override), mpOverride: num(r.mp_override),
  sprite: r.sprite_path, version: r.data_version,
})).filter(c => c.id);

// ---- supporting tables (loaded for later features) ----
const relics = table('relic.csv');
const skills = table('skill.csv');
const traits = table('trait.csv');
const distortions = table('distortion.csv');
const glossary = table('glossary.csv');

const data = {
  version: '0.9.2',
  builtAt: null,               // stamped by caller, avoids nondeterminism
  classes, relics, skills, traits, distortions, glossary,
};

const out = `// AUTO-GENERATED by tools/build-data.mjs — do not edit by hand.\nwindow.TBC = ${JSON.stringify(data)};\n`;
writeFileSync(join(ROOT, 'data', 'data.js'), out);
console.log(`data.js written: ${classes.length} classes, ${relics.length} relics, ${skills.length} skills, ${traits.length} traits, ${distortions.length} distortions, ${glossary.length} glossary`);
